### ISSUE TITLE
python3 -m CustomWhisper -c <project name> -dn <True,False (for denoise active or deactive)>?

### ISSUE THREAD

**Issue by silvacarl2** [anshjoseph/WhisperCustom#2]
Do you have a specific example of this:

python3 -m CustomWhisper -c <project name> -dn <True,False (for denoise active or deactive)>?

what should CustomWhisper be set to so above command line will work?

**Comment by anshjoseph** [comment]
you can do something like this 
python3 -m CustomWhisper -c  MyServer -dn true

best way is to clone the repo, this approach may cause bug's because it not that tested, if any issues while doing this you can contact me at ranshjosrph@gmail.com

**Comment by silvacarl2** [comment]
i will test this out again.
