### ISSUE TITLE
is there a docker version of this someplace?

### ISSUE THREAD

**Issue by silvacarl2** [anshjoseph/WhisperCustom#3]
is there a docker version of this someplace?

**Comment by anshjoseph** [comment]
there is docker file, you can run it but change model as per your need

**Comment by silvacarl2** [comment]
we get this error when trying to build the docker:

Building wheels for collected packages: WhisperLive, openai-whisper, PyAudio
  Building wheel for WhisperLive (pyproject.toml): started
  Building wheel for WhisperLive (pyproject.toml): finished with status 'done'
  Created wheel for WhisperLive: filename=WhisperLive-1.1.0-py3-none-any.whl size=12875 sha256=91d3044fcf574c1e3cb32a6cffe8494dbbc9fa367cabd6929b4d5614640ae063
  Stored in directory: /tmp/pip-ephem-wheel-cache-kbvjzn4f/wheels/d2/4b/68/b8568517986ddfe2a736062b79a5a2dace6a98f742b84af9e4
  Building wheel for openai-whisper (pyproject.toml): started
  Building wheel for openai-whisper (pyproject.toml): finished with status 'done'
  Created wheel for openai-whisper: filename=openai_whisper-20231117-py3-none-any.whl size=801363 sha256=85864d27af46bba9c24807412f5a8d2941f38cf705e68bd4e1a46f7aa068fa66
  Stored in directory: /root/.cache/pip/wheels/d0/85/e1/9361b4cbea7dd4b7f6702fa4c3afc94877952eeb2b62f45f56
  Building wheel for PyAudio (pyproject.toml): started
  Building wheel for PyAudio (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for PyAudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/pyaudio
      copying src/pyaudio/__init__.py -> build/lib.linux-x86_64-cpython-310/pyaudio
      running build_ext
      building 'pyaudio._portaudio' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/src
      creating build/temp.linux-x86_64-cpython-310/src/pyaudio
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include -I/usr/include -I/usr/local/include/python3.10 -c src/pyaudio/device_api.c -o build/temp.linux-x86_64-cpython-310/src/pyaudio/device_api.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyAudio
Successfully built WhisperLive openai-whisper
Failed to build PyAudio
ERROR: Could not build wheels for PyAudio, which is required to install pyproject.toml-based projects

**Comment by anshjoseph** [comment]
FROM python:3.10.13-slim

RUN apt-get update && apt-get install libgomp1 git -y
RUN apt-get -y update && apt-get -y upgrade && apt-get install -y --no-install-recommends ffmpeg
RUN apt-get -y install build-essential
RUN apt-get -y install portaudio19-dev
RUN git clone https://github.com/anshjoseph/WhisperCustom@master
WORKDIR streaming-whisper-server
RUN pip install -e .
RUN pip install git+https://github.com/SYSTRAN/faster-whisper.git
RUN pip install transformers

RUN ct2-transformers-converter --model openai/whisper-small --copy_files preprocessor_config.json --output_dir ./Server/ASR/whisper_small --quantization float16
WORKDIR Server
EXPOSE 9000
CMD ["python3", "Server.py", "-p", "9000"]

**Comment by anshjoseph** [comment]
try to do this

**Comment by silvacarl2** [comment]
TESTING IT NOW!  8-)

**Comment by silvacarl2** [comment]
ok, made a few changes to dockerfile:

FROM python:3.10.13-slim

RUN apt-get update && apt-get install libgomp1 git -y
RUN apt-get -y update && apt-get -y upgrade && apt-get install -y --no-install-recommends ffmpeg
RUN apt-get -y install build-essential
RUN apt-get -y install portaudio19-dev
# Clone the repository
**RUN git clone https://github.com/anshjoseph/WhisperCustom.git**

# Change the working directory to the cloned repository's directory
**WORKDIR WhisperCustom**

# Install the Python package
RUN pip install -e .

RUN pip install git+https://github.com/SYSTRAN/faster-whisper.git
RUN pip install transformers

RUN ct2-transformers-converter --model openai/whisper-small --copy_files preprocessor_config.json --output_dir ./Server/ASR/whisper_small --quantization float16
WORKDIR Server
EXPOSE 9000
CMD ["python3", "Server.py", "-p", "9000"]

**Comment by anshjoseph** [comment]
it' working right ?, if you have any question you can mail me, or me can
schedule a meet
